#!/bin/bash

#CREAR UN FIREWALL CON POLITICAS RESTRICTIVAS TANTO DE SALIDA COMO DE ENTRADA
#Y QUE NOS PODAMOS CONECTAR REMOTAMENTE Y QUE ADEMAS CUALQUIERA NOS PUEDA ENVIAR
#Y CONTESTAR EN NUESTRO PROTOCOLO EFTP. LA MAQUINA WINDOEWS SERA LA UNICA QUE SE
#PUEDA CONECTAR A LA MAQUINA VIRTUAL 
#

./firewall_reset.sh

iptables -P INPUT DROP 
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

iptables -A INPUT -p tcp --dport 22 -s 172.31.98.194 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 22 -d 172.31.98.194 -j ACCEPT

#RECIBIR DATOS
iptables -A INPUT -p tcp --dport 3333 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 3333 -j ACCEPT

#ENVIAR RESPUESTAS
iptables -A OUTPUT -p tcp --dport 3333 -j ACCEPT
iptables -A INPUT -p tcp --sport 3333 -j ACCEPT

